### ISSUE TITLE
PB.grpc does not exist

### ISSUE THREAD

**Issue by angelcervera** [trueaccord/ScalaPB#125]
In the documentation for version 0.4.20 (http://trueaccord.github.io/ScalaPB/sbt-settings.html) said 

> GRPC
> Generating GRPC stubs for services is enabled by default. To disable:
> PB.grpc := false

But PB.grpc is not a member of ScalaPbPlugin.

**Comment by thesamet** [comment]
Thanks for reporting, I updated the page. The short version is that this is 0.5.x setting. if you are on 0.4.x then services will not be generated anyway.

**Comment by angelcervera** [comment]
Hi @thesamet
Is 0.5 ready for production?
I am starting to develop library, so I don't care for a short time production availability.
If it will be ready in few months or if it is not going to change a lot in the generated code, for me it is ok.

What do you think? branch 0.5 or 0.4?

**Comment by eiennohito** [comment]
@angelcervera Why do you need to depend on implementation details?

Interface should not change much I hope.

**Comment by angelcervera** [comment]
@eiennohito Sorry because the confusion. I was asking about changes in the interface. I don't want to start to use a version whose interface is not mature enough.

**Comment by thesamet** [comment]
0.5.x is in active development, yet I am not anticipating breaking changes to the generated code. We're generally adding features in a backwards compatible way.

"production ready" means different things to different people :), We are happily using 0.5.x it in production at TrueAccord, though 0.5.x relies on protobuf 3.0.0-beta-something. 

I'd recommend not building anything new on top of 0.4.x since we know the generated code is not compatible with 0.5.x (though the changes are pretty small)
