### ISSUE TITLE
Should use declared package name

### ISSUE THREAD

**Issue by plaflamme** [trueaccord/ScalaPB#8]
For projects that don't care about the Java bindings, it should be possible to get ScalaPB to use the declared package instead of generating a different one.

**Comment by thesamet** [comment]
I am concerned about supporting two output modes (and duplicating the tests, and edge cases that this can create), and my preference here would be to stay close to the naming conventions made by the official Java protocol buffere generator.

The official Java protocol buffer generator does a similar thing: it wraps the classes generated from each proto file inside a public static class with a name that is derived from the proto file name. So although your messages are technically inside the declared Java package, their fully qualified class name contains the proto file name.

I am not completely sure why this is done this way in the Java generator, perhaps for being able to have few the same message names in two proto files and in the same package (which is not necessarily a good thing, but some projects are probably already be in this situation). 

In ScalaPB, I wanted to avoid the outer class approach since it will force us to have one big Scala class for each protocol buffer. Breaking it to smaller files in sub-packages allows the namespace to look similar to Java, but also enjoy better support for incremental compilation in SBT.

**Comment by plaflamme** [comment]
It has more to do with how `protoc` behaves in general.

The protobuf syntax has package declaration that serves 2 purposes: namespace within `.proto` files and namespace for generated code.

They support overriding the package name for Java (through `option java_package`) because typical proto package names don't "look" like Java package names, as described [here](https://developers.google.com/protocol-buffers/docs/reference/java-generated#package).

The outer class in Java is required because extensions generate simple values that can't live at top-level in Java.

Based on this, I would expect ScalaPB to behave similarly, which is to say that the package declaration within the proto files is respected (either through the `package` keyword or `java_package` option).

ScalaPB can still generate classes in their own file within that package (to get incremental compile goodness). Problems would only happen if someone has created a name collision in 2 separate `.proto` files that declare the same `package` AND that are compiled separately (because `protoc` would choke otherwise).

My situation is that I'd like to move from ScalaBuff to ScalaPB, but it requires that I import `n` new packages everywhere in my codebase (`n` being the number of `.proto` files I have). I could "trick" ScalaPB into generating the package I want, but I would need to merge files together and change their package declaration. I can see this being a much bigger problem for large projects and will definitely hurt ScalaPB's adoption.

One way to support this without breaking the whole ScalaPB world would be to declare an `option` for either `scala_package` or `scala_package_per_file = true/false`.

**Comment by thesamet** [comment]
Oh - I didn't consider file-level custom options for this (I thought only setting this through compiler plugin parameters). In this case, overriding the default settings would require the user to add an import for a "scalapb.proto" and adding something that looks like this in all their protos:

    option (scala_pb.scala_package_per_file) = false;

Is this something that will be acceptable for your use case? Then maybe the protoc plugin can have a setting to override the settings for projects who do not want to add the custom option to every file.

**Comment by plaflamme** [comment]
Yes, that's what I had in mind.

I think ScalaPB could expose several other options to control how it generates Scala case classes as well. So I'd be for using `option` for this. A top-level setting would be nice as well since you probably don't want to do this on a subset of your `.proto` files. Finally, I'd suggest `scala_package` option which more closely matches the java generator and makes more sense as a per-file setting.

**Comment by plaflamme** [comment]
Cool! I'll give this a try. Thanks for considering and implementing this!

**Comment by thesamet** [comment]
You're welcome. This feature has been shipped in v0.4.2
