### ISSUE TITLE
Protobuf 2.x support

### ISSUE THREAD

**Issue by simonstuck** [trueaccord/ScalaPB#88]
From the documentation it seems as if both protobuf 2.6.x and 3.x should be supported on the master branch. What does this mean in terms of the protobuf-java dependency? Is it possible to generate sources that only take protobuf-java version 2.6.x?

**Comment by thesamet** [comment]
Haven't tried. scalapb-runtime depends on protobuf-java v3 so maybe it's
possible to exclude this dependency and try to depend on protobuf 2.6.x.
Closing this issue for now since we use Github issues for bug tracking.
You're welcome to post on this to our google group/gitter.

On Thu, Feb 18, 2016 at 3:05 PM, Simon Stückemann <notifications@github.com>
wrote:

> From the documentation it seems as if both protobuf 2.6.x and 3.x should
> be supported on the master branch. What does this mean in terms of the
> protobuf-java dependency? Is it possible to generate sources that only take
> protobuf-java version 2.6.x?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trueaccord/ScalaPB/issues/88>.
>



-- 
-Nadav
