### ISSUE TITLE
CameCase issue

### ISSUE THREAD

**Issue by cheleb** [trueaccord/ScalaPB#94]
Hi,
  I've encountered an issue with camel casing in ScalaPB, when digit follow an undescore. Illustration of the issue below:

myemnum {
IAB1_1 = 1;   
IAB11 = 181;   
}

Those two entry with conflict when translated in scala class to: isIab11.

I've made a first [fix [0]](https://github.com/tabmo/ScalaPB/commit/1d4aa594079e5c7ad78516bbb8b8fbdef6bd4d45), that work until java stuff are implied, by this I mean that scala classes are generated but e2e.sh fails because some java generated elsewhere, I could not find where. Any clues ?

Thanks
(0) : [https://github.com/tabmo/ScalaPB/commit/1d4aa594079e5c7ad78516bbb8b8fbdef6bd4d45](https://github.com/tabmo/ScalaPB/commit/1d4aa594079e5c7ad78516bbb8b8fbdef6bd4d45)
Olivier

**Comment by thesamet** [comment]
I pushed a commit that does something similar to what Java protoc is doing (adding _1, _2, until an available name is found). The issue is beyond underscore between digits, before this change: A_B_C and A__B__C would end up generating "def isABC". This scheme doesn't generate the optimal names for the enums in OpenRTB though.
